### ISSUE TITLE
Errors in `generate_flow_arflow.py` 

### ISSUE THREAD

**Issue by keunjook** [ponimatkin/ssl-vos#1]
HI! I just got to get interested in the paper.

```
Traceback (most recent call last):
  File "generate_flow_arflow.py", line 13, in <module>
    from config import DATA_PATH, MAX_FLOW_VAL
ImportError: cannot import name 'MAX_FLOW_VAL' from 'config'
```

Also the following import would fail.
```
from utils.flow_utils import quantize_flow 
```

**Comment by ponimatkin** [comment]
Hi @keunjook, thanks for showing interest in our project!

The commit c373d69aeeb2616a70eabbeb9edc5acd32525c61 fixes the issue. At the first stages of our project we experimented with flow quantization, which we have ultimately abandoned later on as it was complicating the pipeline. I forgot to remove those fragments from the final code version.

Feel free to reopen the issue if you'll have some more issues related to this.
