### ISSUE TITLE
RAFT command

### ISSUE THREAD

**Issue by TonyLianLong** [ponimatkin/ssl-vos#2]
Thanks for the amazing work!

It seems that the README only includes ARFlow command. What is the command to extract raft flow?

Seems that `generate_flow_raft.py` accepts a `--model` argument. What should this be?

**Comment by ponimatkin** [comment]
Hi, @TonyLianLong, thanks for showing interest in our work!

In f2efe984ec2123b194a55ec6667400c7b6358510 I've addressed the issue. When you download the models via `bash download_models.sh` you'll find a `models` folder with RAFT and DINO weights in it. I've set `raft-sintel.pth` to be the default weights, but you can try others by simply calling a different weights file, i.e. with `--model models/raft-chairs.pth` and so on.

I hope this helps!
